title: <p align="center"> Om Prakash </p>
logo: /assets/img/Om Prakash.jpg

description:
  <p align="center"> |
  <a href="https://www.linkedin.com/in/om-prakash-43755921//">LinkedIn</a> |
  <a href="https://github.com/gitmydshub">GitHub</a>
  
  <br>   
  Data science enthusiast
  <br>
  </p>



theme: jekyll-theme-minimal
